package al.rb.booking
/**
 * (ITT) Image Tag Type Codes (OTA 2014B) — Implemented¶
 * https://connect.booking.com/user_guide/site/en-US/codes-itt/
 */
enum ImageTagTypeCode {
    Shower(1, "Shower"),
    Toilet(2, "Toilet"),
    Property_building(3, "Property building"),
    Patio(4, "Patio"),
    Nearby_landmark(5, "Nearby landmark"),
    Staff(6, "Staff"),
    Restaurant_places_to_eat(7, "Restaurant/places to eat"),
    Communal_lounge_TV_room(8, "Communal lounge/ TV room"),
    Facade_entrance(10, "Facade/entrance"),
    Spring(11, "Spring"),
    Bed(13, "Bed"),
    Off_site(14, "Off site"),
    Food_close_up(37, "Food close-up"),
    Day(41, "Day"),
    Night(42, "Night"),
    People(43, "People"),
    Property_logo_or_sign(50, "Property logo or sign"),
    Neighbourhood(55, "Neighbourhood"),
    Natural_landscape(61, "Natural landscape"),
    Activities(70, "Activities"),
    Bird_s_eye_view(74, "Bird's eye view"),
    Winter(81, "Winter"),
    Summer(82, "Summer"),
    BBQ_facilities(87, "BBQ facilities"),
    Billiard(89, "Billiard"),
    Bowling(90, "Bowling"),
    Casino(94, "Casino"),
    Place_of_worship(95, "Place of worship"),
    Children_play_ground(96, "Children play ground"),
    Darts(97, "Darts"),
    Fishing(100, "Fishing"),
    Game_Room(102, "Game Room"),
    Garden(103, "Garden"),
    Golfcourse(104, "Golfcourse"),
    Horse_riding(106, "Horse-riding"),
    Hot_Spring_Bath(107, "Hot Spring Bath"),
    Hot_Tub(108, "Hot Tub"),
    Karaoke(112, "Karaoke"),
    Library(113, "Library"),
    Massage(114, "Massage"),
    Minigolf(115, "Minigolf"),
    Nightclub_DJ(116, "Nightclub / DJ"),
    Sauna(124, "Sauna"),
    On_site_shops(125, "On-site shops"),
    Ski_School(128, "Ski School"),
    Skiing(131, "Skiing"),
    Snorkeling(133, "Snorkeling"),
    Solarium(134, "Solarium"),
    Squash(137, "Squash"),
    Table_tennis(141, "Table tennis"),
    Steam_room(143, "Steam room"),
    Bathroom(153, "Bathroom"),
    TV_and_multimedia(154, "TV and multimedia"),
    Coffee_tea_facilities(155, "Coffee/tea facilities"),
    View_from_property_room(156, "View (from property/room)"),
    Balcony_Terrace(157, "Balcony/Terrace"),
    Kitchen_or_kitchenette(158, "Kitchen or kitchenette"),
    Living_room(159, "Living room"),
    Lobby_or_reception(160, "Lobby or reception"),
    Lounge_or_bar(161, "Lounge or bar"),
    Spa_and_wellness_centre_facilities(164, "Spa and wellness centre/facilities"),
    Fitness_centre_facilities(165, "Fitness centre/facilities"),
    Food_and_drinks(167, "Food and drinks"),
    Other(172, "Other"),
    Photo_of_the_whole_room(173, "Photo of the whole room"),
    Business_facilities(177, "Business facilities"),
    Banquet_Function_facilities(178, "Banquet/Function facilities"),
    Decorative_detail(179, "Decorative detail"),
    Seating_area(182, "Seating area"),
    Floor_plan(183, "Floor plan"),
    Dining_area(184, "Dining area"),
    Beach(185, "Beach"),
    Aqua_park(186, "Aqua park"),
    Tennis_court(187, "Tennis court"),
    Windsurfing(188, "Windsurfing"),
    Canoeing(189, "Canoeing"),
    Hiking(190, "Hiking"),
    Cycling(191, "Cycling"),
    Diving(192, "Diving"),
    Kids_s_club(193, "Kids's club"),
    Evening_entertainment(194, "Evening entertainment"),
    Logo_Certificate_Sign(197, "Logo/Certificate/Sign"),
    Animals(198, "Animals"),
    Bedroom(199, "Bedroom"),
    Communal_kitchen(204, "Communal kitchen"),
    Autumn(205, "Autumn"),
    On_site(240, "On site"),
    Meeting_conference_room(241, "Meeting/conference room"),
    Food(242, "Food"),
    Text_overlay(245, "Text overlay"),
    Pets(246, "Pets"),
    Guests(247, "Guests"),
    City_view(248, "City view"),
    Garden_view(249, "Garden view"),
    Lake_view(250, "Lake view"),
    Landmark_view(251, "Landmark view"),
    Mountain_view(252, "Mountain view"),
    Pool_view(253, "Pool view"),
    River_view(254, "River view"),
    Sea_view(255, "Sea view"),
    Street_view(256, "Street view"),
    Area_and_facilities(257, "Area and facilities"),
    Supermarket_grocery_shop(258, "Supermarket/grocery shop"),
    Shopping_Area(259, "Shopping Area"),
    Swimming_pool(260, "Swimming pool"),
    Sports(261, "Sports"),
    Entertainment(262, "Entertainment"),
    Meals(263, "Meals"),
    Breakfast(264, "Breakfast"),
    Continental_breakfast(265, "Continental breakfast"),
    Buffet_breakfast(266, "Buffet breakfast"),
    Asian_breakfast(267, "Asian breakfast"),
    Italian_breakfast(268, "Italian breakfast"),
    English_Irish_breakfast(269, "English/Irish breakfast"),
    American_breakfast(270, "American breakfast"),
    Lunch(271, "Lunch"),
    Dinner(272, "Dinner"),
    Drinks(273, "Drinks"),
    Alcoholic_drinks(274, "Alcoholic drinks"),
    Non_alcoholic_drinks(275, "Non alcoholic drinks"),
    Seasons(276, "Seasons"),
    Time_of_day(277, "Time of day"),
    Location(278, "Location"),
    Sunrise(279, "Sunrise"),
    Sunset(280, "Sunset"),
    children(281, "children"),
    young_children(282, "young children"),
    older_children(283, "older children"),
    group_of_guests(284, "group of guests"),
    cot(285, "cot"),
    bunk_bed(286, "bunk bed"),
    Certificate_Award(287, "Certificate/Award"),
    Open_Air_Bath(289, "Open Air Bath"),
    Public_Bath(290, "Public Bath"),
    Family(291, "Family")

    private final int code
    private final String name

    private ImageTagTypeCode(code, String name) {
        this.code = code
        this.name = name
    }

    String getAttraction() {
        return name
    }

    int getCode() {
        return code
    }
    static constraints = {
    }
}
