package al.rb.booking
/**
 * TODO Add Booking Codes https://connect.booking.com/user_guide/site/en-US/codes-rma/
 */
enum RoomAmenityCode {
    AIR_CONDITIONING(2, 'AIR CONDITIONING'),
    ALARM_CLOCK(3, "ALARM CLOCK"),
    AMFM_RADIO(5, "AM/FM RADIO"),
    BARBEQUE_GRILLS(8, "BARBEQUE GRILLS"),
    BATH_TUB_WITH_SPRAY_JETS(9, "BATH TUB WITH SPRAY JETS"),
    BATHROBE(10, "BATHROBE"),
    BATHROOM_AMENITIES_FREE_TOILETRIES(11, "BATHROOM AMENITIES (FREE TOILETRIES)"),
    BATHTUB(13, "BATHTUB"),
    BATHTUB_ONLY(14, "BATHTUB ONLY"),
    BATH_OR_SHOWER(15, "BATH OR SHOWER"),
    BIDET(16, "BIDET"),
    CABLE_TELEVISION(18, "CABLE TELEVISION"),
    COFFEE_TEA_MAKER(19, "COFFEE/TEA MAKER"),
    COLOR_TELEVISION(20, "COLOR TELEVISION"),
    COMPUTER(21, "COMPUTER"),
    CONNECTING_ROOMS(22, "CONNECTING ROOMS"),
    CORDLESS_PHONE(25, "CORDLESS PHONE"),
    DESK(28, "DESK"),
    DESK_WITH_LAMP(29, "DESK WITH LAMP"),
    DISHWASHER(32, "DISHWASHER"),
    FAX_MACHINE(38, "FAX MACHINE"),
    FIREPLACE(41, "FIREPLACE"),
    FREE_MOVIES_VIDEO(46, "FREE MOVIES/VIDEO"),
    FULL_KITCHEN(47, "FULL KITCHEN"),
    GRECIAN_TUB(49, "GRECIAN TUB"),
    HAIRDRYER(50, "HAIRDRYER"),
    INTERNET_ACCESS(54, "INTERNET ACCESS"),
    IRON_IRONING_FACILITIES(55, "IRON (IRONING FACILITIES)"),
    IRONING_BOARD(56, "IRONING BOARD"),
    WHIRPOOL(57, "WHIRPOOL"),
    KITCHEN(59, "KITCHEN"),
    KITCHEN_SUPPLIES(60, "KITCHEN SUPPLIES"),
    KITCHENETTE(61, "KITCHENETTE"),
    LAPTOP(63, "LAPTOP"),
    LARGE_DESK(64, "LARGE DESK"),
    MICROWAVE(68, "MICROWAVE"),
    MINIBAR(69, "MINIBAR"),
    MULTI_LINE_PHONE(72, "MULTI-LINE PHONE"),
    OVEN(77, "OVEN"),
    PAY_PER_VIEW_MOVIES_ON_TV(78, "PAY PER VIEW MOVIES ON TV"),
    PHONE_IN_BATHROOM(80, "PHONE IN BATHROOM"),
    PLATES_AND_BOWLS(81, "PLATES AND BOWLS"),
    PRIVATE_BATHROOM(85, "PRIVATE BATHROOM"),
    REFRIGERATOR(88, "REFRIGERATOR"),
    REFRIGERATOR_WITH_ICE_MAKER(89, "REFRIGERATOR WITH ICE MAKER"),
    SAFE(92, "SAFE"),
    SEPARATE_CLOSET(94, "SEPARATE CLOSET"),
    SHOWER_ONLY(97, "SHOWER ONLY"),
    SILVERWARE_UTENSILS(98, "SILVERWARE/UTENSILS"),
    SITTING_AREA(99, "SITTING AREA"),
    SPEAKER_PHONE(103, "SPEAKER PHONE"),
    STOVE(105, "STOVE"),
    TELEPHONE_FOR_HEARING_IMPAIRED(108, "TELEPHONE FOR HEARING IMPAIRED"),
    VCR_MOVIES(115, "VCR MOVIES"),
    VIDEO_GAMES(117, "VIDEO GAMES"),
    WAKE_UP_CALLS(119, "WAKE-UP CALLS"),
    WIRELESS_INTERNET_CONNECTION(123, "WIRELESS INTERNET CONNECTION"),
    AIR_CONDITIONING_INDIVIDUALLY_CONTROLLED_IN_ROOM(126, "AIR CONDITIONING INDIVIDUALLY CONTROLLED IN ROOM"),
    BATHTUB_WHIRLPOOL_SEPARATE(127, "BATHTUB &WHIRLPOOL SEPARATE"),
    CD_PLAYER(129, "CD PLAYER"),
    DESK_WITH_ELECTRICAL_OUTLET(133, "DESK WITH ELECTRICAL OUTLET"),
    MARBLE_BATHROOM(138, "MARBLE BATHROOM"),
    LIST_OF_MOVIE_CHANNELS_AVAILABLE(139, "LIST OF MOVIE CHANNELS AVAILABLE"),
    OVERSIZED_BATHTUB(141, "OVERSIZED BATHTUB"),
    SHOWER(142, "SHOWER"),
    SOUNDPROOFED_ROOM(144, "SOUNDPROOFED ROOM"),
    TABLES_AND_CHAIRS(146, "TABLES AND CHAIRS"),
    TWO_LINE_PHONE(147, "TWO-LINE PHONE"),
    WASHER_DRYER(149, "WASHER/DRYER1"),
    SEPARATE_TUB_AND_SHOWER(155, "SEPARATE TUB AND SHOWER"),
    CEILING_FAN(157, "CEILING FAN"),
    CNN_AVAILABLE(158, "CNN AVAILABLE"),
    CLOSETS_IN_ROOM(162, "CLOSETS IN ROOM"),
    DVD_PLAYER(163, "DVD PLAYER"),
    MINI_REFRIGERATOR(164, "MINI-REFRIGERATOR"),
    SELF_CONTROLLED_HEATING_COOLING_SYSTEM(166, "SELF-CONTROLLED HEATING/COOLING SYSTEM"),
    TOASTER(167, "TOASTER"),
    SHARED_BATHROOM(193, "SHARED BATHROOM"),
    TELEPHONE_TDD_TEXTPHONE(194, "TELEPHONE TDD/TEXTPHONE"),
    SATELLITE_TELEVISION(210, "SATELLITE TELEVISION"),
    IPOD_DOCKING_STATION(214, "IPOD DOCKING STATION"),
    SATELLITE_RADIO(217, "SATELLITE RADIO"),
    VIDEO_ON_DEMAND(218, "VIDEO ON DEMAND"),
    GULF_VIEW(220, "GULF VIEW"),
    MOUNTAIN_VIEW(223, "MOUNTAIN VIEW"),
    OCEAN_VIEW(224, "OCEAN VIEW"),
    SLIPPERS(228, "SLIPPERS"),
    CHAIR_PROVIDED_WITH_DESK(230, "CHAIR PROVIDED WITH DESK"),
    LUXURY_LINEN_TYPE(234, "LUXURY LINEN TYPE"),
    PRIVATE_POOL(245, "PRIVATE POOL"),
    HD(246, "HIGH DEFINITION (HD) FLAT PANEL TELEVISION - 32 INCHES OR GREATER"),
    TV(251, "TV"),
    VIDEO_GAME_PLAYER(254, "VIDEO GAME PLAYER"),
    DINING_ROOM_SEATS(256, "DINING ROOM SEATS"),
    MOBILE_CELLULAR_PHONES(258, "MOBILE/CELLULAR PHONES"),
    MOVIES(259, "MOVIES"),
    MULTIPLE_CLOSETS(260, "MULTIPLE CLOSETS"),
    SAFE_LARGE_ENOUGH_TO_ACCOMMODATE_A_LAPTOP(262, "SAFE LARGE ENOUGH TO ACCOMMODATE A LAPTOP"),
    BLURAY_PLAYER(265, "BLURAY PLAYER"),
    NON_ALLERGENIC_ROOM(268, "NON-ALLERGENIC ROOM"),
    SEATING_AREA_WITH_SOFA_CHAIR(270, "SEATING AREA WITH SOFA/CHAIR"),
    SEPARATE_TOILET_AREA(271, "SEPARATE TOILET AREA"),
    WIDESCREEN_TV(273, "WIDESCREEN TV"),
    SEPARATE_TUB_OR_SHOWER(276, "Separate tub or shower" )

    private final int code
    private final String name

    private RoomAmenityCode(code, String name) {
        this.code = code
        this.name = name
    }

    String getAttraction() {
        return name
    }

    int getCode() {
        return code
    }

    static constraints = {
    }
}
